-- master_game_list
INSERT INTO public.master_game_list (game_id, game_name, description, category, difficulty_level) VALUES
(1, '185', 'Formula: 185 ______ Walk into a bar. Bartender says, "I can''t serve you 185 _______". 185 _______ say, "Why not?". Bartender says, "(insert bad pun here)".', 'Medley/Group/Challenge', NULL),
(2, '4 Track', NULL, 'Game Based', NULL),
(3, 'Action Line', 'Imitate Schwarzenegger. Deliver cheesy one liner that''s a pun on the object suggested', 'Medley/Group/Challenge', NULL),
(4, 'All About... Armando', 'Scenes inspired by a guest monologist. Buble scenes inspired by monologue, tangeant scenes from there. Combo of Armando and BSM.', 'Deconstruction Style', NULL),
(5, 'Alphabet', 'Players must start each subsequent line with the next letter of the alphabet', 'Monkey Wrench', NULL),
(6, 'Armandito', 'Scenes inspired by a monologist', 'Deconstruction Style', NULL),
(7, 'Armando', 'Scenes inspired by the player''s monlogues', 'Deconstruction Style', NULL),
(8, 'Arms Expert', 'An audience member comes up on stage, one player interviews while the other sits behind the audience member and plays as their hands.', 'Audience Participation', NULL),
(9, 'Back in Time', 'Start with a scene and then every subsequent scene happens before the scene that came before it.', 'Game Based', NULL),
(10, 'Bad Pickup Line', 'An audience member comes up on stage and cast tries to "pick them up" using terrible pick up lines', 'Audience Participation', NULL),
(11, 'Beastie Raps', 'Challenge game where players try to out rhyme each other', 'Medley/Group/Challenge', NULL),
(12, 'Bedtime Story', 'Musical Narrative led by a story teller', 'Musical', NULL),
(13, 'Beer Slacker Mice', 'A grounded scene, then we follow the funny. Eventually we make our way back to that grounded scene, and repeat', 'Game Based', NULL),
(14, 'Bouncer', '10 Celebrities, 10 fictional characters, 10 historical figures. the guesser is a bouncer that needs to guess them before allowing them in the club.', 'Guessing', NULL),
(15, 'By the Numbers', '2 of the 3 players must speak only using a pre-determined number of words in each line', 'Monkey Wrench', NULL),
(16, 'Call''ems / Pillars', 'Two audience members are brought on stage, and have to fill in the blanks during the scene', 'Audience Participation', NULL),
(17, 'Chairs', 'Players pick up chairs and walk around until the audience says "Stop". This position inspires the scene.', 'Duo', NULL),
(18, 'Complaint Department', 'Items need to be returned, the guesser has to figure out what they are.', 'Guessing', NULL),
(19, 'CSI Miami', 'Deliver terrible pun based a la David Carruso on CSI Miami. "Looks like this guy... ______________"', 'Medley/Group/Challenge', NULL),
(20, 'Day in the Life', 'An audience member is interviewed and the players perform a recreation of their day, progressively getting faster', 'Audience Participation', NULL),
(21, 'Dead Bodies', 'One player continues playing despite their fellow players "dying" a few lines into thier "scene"', 'Monkey Wrench', NULL),
(22, 'Deconstruction', '3 grounded scenes inspired by three suggestions. Then players perform scenes by deconstructing those.', 'Deconstruction Style', NULL),
(23, 'Docudrama', 'Scenes happen. Occasionally someone will sit downstage center and deliver a "testemonial" that advances the plot', 'Scene Based', NULL),
(24, 'Documentary', 'An improvised documentary', 'Scene Based', NULL),
(25, 'Don''t Make Me Laugh', 'Challenge game. Players perform a scene trying NOT to make the audience laugh.', 'Medley/Group/Challenge', NULL),
(26, 'Doo Ron Ron', 'Challenge game. Rhyming game based on the titular song.', 'Medley/Group/Challenge', NULL),
(27, 'Double Entendre', 'Bad pun "I like my women/men how I like my______________"', 'Medley/Group/Challenge', NULL),
(28, 'Drinking Song (Cuban, Mexican, Irish)', 'A Drinking song by four players one line at a time.', 'Musical', NULL),
(29, 'Emotions', 'A caller randomly calls out emotions previously suggested by the audience affecting the scene.', 'Monkey Wrench', NULL),
(30, 'Evil Chewing Gum', 'There''s an evil stick of chewing gum voiced by a player off stage.', 'Monkey Wrench', NULL),
(31, 'Excuses', 'The guesser arrives late and needs to guess why they''re late. Two other players mime clues behind the caller''s back', 'Guessing', NULL),
(32, 'Famous Person Who', 'Two audience members are brought on stage, and the cast treats one as a celebrity of the other''s choosing. Audience member needs to guess who they are.', 'Audience Participation', NULL),
(33, 'First Line / Last Line', 'Backline game. Players start each subsequent scene with the last line of the scene that came before it.', 'Medley/Group/Challenge', NULL),
(34, 'Follow the Leaver', 'Every time a character leaves a scene we follow that character into the next scene.', 'Game Based', NULL),
(35, 'Forward Reverse', 'Caller forwards and reverses the scene in play', 'Monkey Wrench', NULL),
(36, 'Four Corners', 'Four scenes happen on a rotation. Caller moves them left and right.', 'Scene Based', NULL),
(37, 'Four Corners 2-1-1', 'A Mashup of Four Corners and Pick-a-line 411', 'Audience Participation', NULL),
(38, 'Freeze Tag (Normal or Blind)', 'Players perform a scene. Players on backline will freeze them and start an entirely new scene by taking the previous player''s body position.', 'Medley/Group/Challenge', NULL),
(39, 'Funeral', 'Grab three suggestions. Suggestion one gets a grounded scene then play as if it were a Beer Slacker Mice. When it''s time to come back to the grounded scene, do a grounded scene based on suggestion 2. After all three suggestions have been used for grounded scenes, begin to tie it together with callbacks, themes, etc.', 'Deconstruction Style', NULL),
(40, 'Good Bad Ugly', 'Audience members ask questions and the players give them good, bad, and ugly answers', 'Audience Participation', NULL),
(41, 'Harold', 'There are whole books dedicated to this, and there''s no way to explain it without drawing a chart. Audiences love it, improvisors love it.', 'Harold', NULL),
(42, 'Hecklers', 'Players perform a scene while other players sit in the audience and heckle.', 'Scene Based', NULL),
(43, 'Ho-down', 'A western song one line at a time', 'Musical', NULL),
(44, 'Home Shopping Network', 'Three items, plus what''s weird about them. Basically a game of charades with a home shopping network theme.', 'Guessing', NULL),
(45, 'How did we get in here', 'To Players pickup a story where they''re in prison', 'Duo', NULL),
(46, 'Impossible Scene', 'Challenge Game. Must perform a scene without using "Me, My, or I, or asking a question."', 'Medley/Group/Challenge', NULL),
(47, 'Improv Shakespeare', 'An improvised narrative in the style of a Shakespearean play', 'Scene Based', NULL),
(48, 'Interrogation', 'Crime Locatio Object - The crook needs to guess what they did while the detectives dole out clues', 'Guessing', NULL),
(49, 'Intervention', 'A player is given an addiction. We see it play out throughout their lives.', 'Scene Based', NULL),
(50, 'Invisibility', 'One character is "invisible" voiced by a player off stage', 'Monkey Wrench', NULL),
(51, 'Jeopardy', 'Audience submits suggestions, and the players play a round of Double Jeopardy before moving onto Final Jeopardy', 'Audience Participation', NULL),
(52, 'JTF Rap', 'Get a current event and rap about it.', 'Medley/Group/Challenge', NULL),
(53, 'Kick-It', 'Players perform a scne. Occasionally the beatboxer or caller will shout Kick-It and players have to rap until the caller says "Word" / Musical Narrative led by a beatboxer', 'Monkey Wrench', NULL),
(54, 'Living Room', 'Everyone sits living room style and shares truthful stories. Players then perform scenes based on those stories.', 'Deconstruction Style', NULL),
(55, 'Love Machine', 'Audience member is brought up, blindfolded, and plays a round of the dating game with pre-determined characters', 'Audience Participation', NULL),
(56, 'Madam Zinda', 'Similar to late excuses. Madam Zinda is a fortune teller who has to guess the fortune. The caller is the client getting his fortune told, and the other two improvisers are "spirits" that silently mime the fortune.', 'Guessing', NULL),
(57, 'Madrigal', '4-5 singers each sing one line to start and then combine in a cacophony of themes.', 'Musical', NULL),
(58, 'Mannequins', 'Two audience members are brought up to move around the players as they please', 'Audience Participation', NULL),
(59, 'Messing', 'Scenes are performed until they reach a high note. Then the players switch into different positions on stage and let this dynamic inspire the next scene.', 'Duo', NULL),
(60, 'Montage', 'A series of scenes inspired by other scenes', 'Scene Based', NULL),
(61, 'Musical Narrative', 'Narrative with musical underscore.', 'Musical', NULL),
(62, 'My Nickname in College', 'A bad pun about why your nickname in college was whatever the audience suggests.', 'Medley/Group/Challenge', NULL),
(63, 'Narrative Montage', 'A series of scenes inspired by other scenes that eventually form a narrative.', 'Scene Based', NULL),
(64, 'New Choice', 'Caller rings a bell and prompts the players to make a new choice and justify.', 'Monkey Wrench', NULL),
(65, 'Nightmare', 'An audience member is interviewed and the players perform a series of scenes deconstructing the interview.', 'Deconstruction Style', NULL),
(66, 'Objection 1.0', 'Players are lawyers in a courtroom discussing two topics. They can Object and a "judge" will sustain or overrule the objection', 'Monkey Wrench', NULL),
(67, 'Objection 2.0', 'Backline game. Similar to Objection 1.0 but less scene based.', 'Medley/Group/Challenge', NULL),
(68, 'Panel of Experts', 'Audience members ask questions and the players give them answers one word at a time', 'Audience Participation', NULL),
(69, 'Party Quirks', 'Guesser is throwing a party, has to guess the party-goer''s quirks', 'Guessing', NULL),
(70, 'Pick-a-Line 1.0', 'Audience members pick 6 lines. Two players then perform a scene, and pick the lines out randomly.', 'Audience Participation', NULL),
(71, 'Pick-a-Line 2.0', 'Audience members submit lines before the show, players perform scenes from the backline occasionally picking out lines to fill the blanks', 'Audience Participation', NULL),
(72, 'Pick-a-Line 4-1-1', 'Players perform a scene occasionally filling in the blanks by reading text messages from audience phones', 'Audience Participation', NULL),
(73, 'Questions', 'Challenge game where players are only allowed to speak using questions.', 'Medley/Group/Challenge', NULL),
(74, 'Rap Scene', 'Similar to Shakespeare but the players recreate the scene using Hip Hop and a Beat Boxer', 'Scene Based', NULL),
(75, 'Repeat Performance', 'Group A of players goes outside. Groub B performs a scene. Group A comes back in to watch Group B perform the same scene in gibberish. Group A then tries to recreate whatever the scene was about.', 'Scene Based', NULL),
(76, 'Reverse Survivor', '1 player stays on stage, the rest outside. Player 1 acts out a scene as if the others are there. Player two comes back in. Player 1 repeats everything exactly as they did originally, while Player 2 joins in. Player 3 enters. player 1 and 2 repeat exactly what they did, while P3 plays. Repeat as needed.', 'Scene Based', NULL),
(77, 'Rick Hop Your Life', 'a combination of Hip Hop your life, and JTF Rap.', 'Medley/Group/Challenge', NULL),
(78, 'Rick-a-Line', 'Pre-prepared lines based on current events. The cast hasn''t seen the lines', 'Audience Participation', NULL),
(79, 'Scene In Verse', 'Each player''s first line must rhyme with the second line of the other player', 'Monkey Wrench', NULL),
(80, 'Shakespeare Scene', 'Players A perform a scene on one side of the stage. Players B then recreate that scene in Shakespearean theme. Repeats until game end.', 'Scene Based', NULL),
(81, 'Sit, stand, bend (lay)', 'One player stands, one player sits, one player either bends or lays', 'Monkey Wrench', NULL),
(82, 'Slaps', 'Challenge Game. using questions or don''t make me laugh, but the losers get smacked in the face by the winners each time they lose a face off.', 'Medley/Group/Challenge', NULL),
(83, 'Sound FX', 'An audience member is brought on stage to perform sound fx for a scene, OR mic is passed around in the audience.', 'Audience Participation', NULL),
(84, 'Speed Dating', 'Players perform a series of scenes by rotating through a speed dating scenario.', 'Game Based', NULL),
(85, 'Spotlight', '3 players try to out-sing each other lounge style.', 'Musical', NULL),
(86, 'Story Story Die', 'Players line up and tell a story with a conductor. If they mess up, they''re eliminated. May or may not include long excruciating death scene.', 'Medley/Group/Challenge', NULL),
(87, 'Story Story Die alt. Instruction Manual', 'Exactly like Story Story Die, except instead of telling a story you''re working through chapters in an instruction manual.', 'Medley/Group/Challenge', NULL),
(88, 'Styles / Genres', 'SImilar to Emotions but with styles of movies', 'Monkey Wrench', NULL),
(89, 'Subconcious Mexican Restaurant', 'Two players are at a Mexican restaurant, occasionally another player will come out and sing their inner thoughts.', 'Musical', NULL),
(90, 'Survivor', 'Players perform a scene. The Audience votes one player out, remaining players need to recreate the scene filling in for that player. Repeat until only one player is doing all the parts', 'Scene Based', NULL),
(91, 'Table For Four', 'Two players perform all the characters at a dinner.', 'Duo', NULL),
(92, 'Ten Scenes', 'Players perform Ten Scenes', 'Scene Based', NULL),
(93, 'Ten Scenes - Toss Up', 'Players perform Ten Scens. Occasionally the audience will throw flags on stage that have been pre-endowed with stipulations. Scenes remain with the stipulation until they are edited.', 'Scene Based', NULL),
(94, 'The Club', 'This opens with everyone except one is dancing in the background of a club. The music is played whle everyone dances along. After a few moments, the last cast member will come from the back, asking the audience member for the name of the club. This is usually a color and then a noun of some sort. Once the suggestions are recieved, the last cast member "finds" the club and then is welcomed. After that, random scenes play that are take place within this club. All scenes are inspired by the suggestion.', 'Open Scenes', NULL),
(95, 'The Event', 'Scenes happen based on their location in time around a central nexus event.', 'Game Based', NULL),
(96, 'The Houdini', NULL, 'Deconstruction Style', NULL),
(97, 'The Mamet', 'The cast starts by scene painting a location. They then play in that location while entering and exiting.', 'Deconstruction Style', NULL),
(98, 'The Maverick (Formally The UCB)', 'An interviewer talks to an audience member and gathers info. The players then perform a scene or scenes based on the information. Repeat as needed.', 'Deconstruction Style', NULL),
(99, 'The Unusuals', 'We see a family and how audience suggested endowments impacts their day.', 'Scene Based', NULL),
(100, 'The Wave', '4 players are two sets of characters at a sporting event. Every time the wave happens the conversation switches between pairs', 'Monkey Wrench', NULL),
(101, 'Things you can say', 'Things you can say to your (Insert audience suggestion) that you can''t say to your sifnificant object.', 'Medley/Group/Challenge', NULL),
(102, 'Things You Never Hear', 'Things you''d never see or here at audience suggested locations or periods in history', 'Medley/Group/Challenge', NULL),
(103, 'Third Date', 'Two players are on a third date.', 'Duo', NULL),
(104, 'Translators', 'Two players perform a scene in gibberish, two other players provide the translation for the scene.', 'Scene Based', NULL),
(105, 'Two-Line Vocab', 'two of the three players are only allowed to speak using two lines supplied to them each by the audience.', 'Monkey Wrench', NULL),
(106, 'Uber Driver', 'Driver picks up fares. Has to guess the client''s quirks', 'Guessing', NULL),
(107, 'Universal Remote', 'Similar to Forward Reverse but with more options limited only by the caller''s imagination', 'Monkey Wrench', NULL),
(108, 'Up Your Alley', 'An audience expert is brought on stage, two players perform as other experts in the same field.', 'Audience Participation', NULL),
(109, 'Wakeup', 'Two players wake up.', 'Duo', NULL),
(110, 'World''s Worst', 'Short scenes based on the worlds worst version of an audience supplied occupation', 'Medley/Group/Challenge', NULL),
(111, 'You Tell Us', 'During the scene the caller stops to ask the audience for suggestions.', 'Audience Participation', NULL),
(112, 'Your Life in Hip Hop', 'Interview an audience member and then rap about their life.', 'Musical', NULL),
(113, 'New Game Test', 'Custom game added from show 11', 'Improv', NULL)
ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.master_game_list','game_id'), COALESCE((SELECT MAX(game_id) FROM public.master_game_list),1), true);
